use utoipa::OpenApi;

use crate::{
    AgentConnection, AgentConnectionStatus, AgentPool, AgentPoolAvailability,
    AgentPoolAvailabilityStatus, AgentPoolJoinRequest, AgentPoolPerson, AgentPoolRequestStatus,
    AgentPoolShareEvidence, AgentPoolUsageMetric, AgentProvider, AuthenticatedUser,
    CompleteAuthorizationRequest, ConnectDeepseekRequest, CreateAgentPoolJoinRequest,
    CreateOrganization, CreatedGatewayKey, DecideAgentPoolJoinRequest, ErrorResponse, GatewayKey,
    HealthResponse, InviteAgentPoolMember, InviteOrganizationMember, LoginRequest, Organization,
    OrganizationAgent, OrganizationAgentDetails, OrganizationAgentListQuery,
    OrganizationInvitation, OrganizationMember, OrganizationOverview, OrganizationPeriodQuery,
    OrganizationUsage, OrganizationUsageBreakdown, OrganizationUsageDay, OrganizationUsageQuery,
    RegisterRequest, SessionResponse, ShareOrganizationAgent, StartAgentConnectionRequest,
    ActionDecision, AuthorizeActionRequest, CreatePlanRequest, ExecutionPlan, PlanStep,
    ReasoningDailyStat, ReasoningEvent, VerificationResult, VerifyOutcomeRequest,
    DecideDeviceAuthorization, DeviceAuthorizationStarted, DeviceAuthorizationToken,
    PendingDeviceAuthorization, PollDeviceAuthorization, StartDeviceAuthorization,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Hub William API",
        description = "Control-plane and gateway API for Hub William agent pools",
        version = "0.1.0"
    ),
    paths(
        crate::health::health,
        crate::auth::register,
        crate::auth::login,
        crate::auth::wallet_nonce,
        crate::auth::wallet_login,
        crate::auth::session,
        crate::auth::logout,
        crate::auth::refresh,
        crate::agent_pools::list,
        crate::agent_pools::create_request,
        crate::agent_pools::decide_request,
        crate::agent_pools::invite_member,
        crate::agent_pools::remove_member,
        crate::organizations::list_organizations,
        crate::organizations::create_organization,
        crate::organizations::list_invitations,
        crate::organizations::accept_invitation,
        crate::organizations::decline_invitation,
        crate::organizations::overview,
        crate::organizations::list_agents,
        crate::organizations::share_agent,
        crate::organizations::unshare_agent,
        crate::organizations::list_members,
        crate::organizations::invite_member,
        crate::organizations::remove_member,
        crate::organizations::usage,
        crate::connections::list_connections,
        crate::connections::start,
        crate::connections::connect_deepseek,
        crate::connections::get_connection,
        crate::connections::refresh_connection,
        crate::connections::complete_authorization,
        crate::connections::disconnect,
        crate::gateway::create_key,
        crate::gateway::list_keys,
        crate::gateway::revoke_key,
        crate::reasoning::plan_handler,
        crate::reasoning::authorize_handler,
        crate::reasoning::verify_handler,
        crate::reasoning::list_events,
        crate::reasoning::daily_stats,
        crate::agent_auth::start_device_authorization,
        crate::agent_auth::poll_device_authorization,
        crate::agent_auth::list_pending_authorizations,
        crate::agent_auth::decide_device_authorization,
        crate::playground::models,
        crate::playground::chat
    ),
    components(schemas(
        crate::playground::PlaygroundModel,
        crate::playground::PlaygroundAttachment,
        crate::playground::PlaygroundRole,
        crate::playground::PlaygroundMessage,
        crate::playground::PlaygroundChatRequest,
        AuthenticatedUser,
        AgentConnection,
        AgentConnectionStatus,
        AgentPool,
        AgentPoolAvailability,
        AgentPoolAvailabilityStatus,
        AgentPoolJoinRequest,
        AgentPoolPerson,
        AgentPoolRequestStatus,
        AgentPoolShareEvidence,
        AgentPoolUsageMetric,
        AgentProvider,
        CompleteAuthorizationRequest,
        ConnectDeepseekRequest,
        CreateAgentPoolJoinRequest,
        CreatedGatewayKey,
        DecideAgentPoolJoinRequest,
        ErrorResponse,
        GatewayKey,
        HealthResponse,
        LoginRequest,
        InviteAgentPoolMember,
        RegisterRequest,
        SessionResponse,
        StartAgentConnectionRequest,
        ActionDecision,
        AuthorizeActionRequest,
        CreatePlanRequest,
        ExecutionPlan,
        PlanStep,
        VerificationResult,
        VerifyOutcomeRequest,
        ReasoningEvent,
        ReasoningDailyStat,
        DecideDeviceAuthorization,
        DeviceAuthorizationStarted,
        DeviceAuthorizationToken,
        PendingDeviceAuthorization,
        PollDeviceAuthorization,
        StartDeviceAuthorization,
        CreateOrganization,
        InviteOrganizationMember,
        Organization,
        OrganizationAgent,
        OrganizationAgentDetails,
        OrganizationAgentListQuery,
        OrganizationInvitation,
        OrganizationMember,
        OrganizationOverview,
        OrganizationPeriodQuery,
        OrganizationUsage,
        OrganizationUsageBreakdown,
        OrganizationUsageDay,
        OrganizationUsageQuery,
        ShareOrganizationAgent,
        crate::auth::WalletLoginRequest,
        crate::auth::WalletNonceRequest,
        crate::auth::WalletNonceResponse
    )),
    tags(
        (name = "auth", description = "Browser account sessions"),
        (name = "agent connections", description = "Encrypted upstream provider connection lifecycle"),
        (name = "agent pools", description = "Public connected account pools and authenticated membership requests"),
        (name = "organizations", description = "Organization membership, shared agents, and recorded usage"),
        (name = "gateway keys", description = "Revocable keys for provider-specific gateway access"),
        (name = "reasoning", description = "SERV Reasoning control plane for agent planning, boundary authorization, and outcome verification"),
        (name = "agent auth", description = "Device authorization flow for agents to obtain scoped gateway keys"),
        (name = "system", description = "Runtime health and diagnostics")
    )
)]
pub struct ApiDoc;
