/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/agent-auth/device": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["start_device_authorization"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-auth/device/decision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["decide_device_authorization"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-auth/device/pending": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_pending_authorizations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-auth/device/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["poll_device_authorization"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_connections"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/deepseek": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["connect_deepseek"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/{connection_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_connection"];
    put?: never;
    post?: never;
    delete: operations["disconnect"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/{connection_id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["complete_authorization"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/{connection_id}/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["refresh_connection"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pool-requests/{request_id}/decision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["decide_request"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pools/{connection_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["invite_member"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pools/{connection_id}/members/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["remove_member"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pools/{connection_id}/requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_request"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["session"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/gateway-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_keys"];
    put?: never;
    post: operations["create_key"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/gateway-keys/{key_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["revoke_key"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reasoning/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["authorize_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reasoning/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_events"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reasoning/events/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["daily_stats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reasoning/plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["plan_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reasoning/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["verify_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ActionDecision: {
      allowed: boolean;
      /** Format: date-time */
      audited_at: string;
      boundary_enforced: string;
      decision_id: string;
      matched_contract?: string | null;
      reason: string;
      reasoner_model: string;
      status: string;
    };
    AgentAuthorizationPrompt: {
      authorization_url: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: int64 */
      poll_after_seconds: number;
      requires_callback_url: boolean;
      user_code?: string | null;
    };
    AgentConnection: {
      account_label?: string | null;
      authorization?: null | components["schemas"]["AgentAuthorizationPrompt"];
      /** Format: date-time */
      created_at: string;
      failure_message?: string | null;
      /** Format: uuid */
      id: string;
      plan?: string | null;
      provider: components["schemas"]["AgentProvider"];
      status: components["schemas"]["AgentConnectionStatus"];
      /** Format: date-time */
      updated_at: string;
    };
    /** @enum {string} */
    AgentConnectionStatus: "pending" | "connected" | "failed" | "disconnected";
    AgentPool: {
      account_label: string;
      agent: string;
      availability: components["schemas"]["AgentPoolAvailability"];
      /** Format: int32 */
      capacity: number;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      members: components["schemas"]["AgentPoolPerson"][];
      owner: components["schemas"]["AgentPoolPerson"];
      plan: string;
      requests: components["schemas"]["AgentPoolJoinRequest"][];
      usage: components["schemas"]["AgentPoolUsageMetric"][];
    };
    AgentPoolAvailability: {
      /** Format: date-time */
      retry_at?: string | null;
      status: components["schemas"]["AgentPoolAvailabilityStatus"];
    };
    /** @enum {string} */
    AgentPoolAvailabilityStatus:
      "active" | "rate_limited" | "half_open" | "reauth_required";
    AgentPoolJoinRequest: {
      avatar_label: string;
      /** Format: uuid */
      id: string;
      reason: string;
      status: components["schemas"]["AgentPoolRequestStatus"];
      telegram: string;
      username: string;
    };
    AgentPoolPerson: {
      avatar_label: string;
      /** Format: date-time */
      joined_at: string;
      share: components["schemas"]["AgentPoolShareEvidence"];
      /** Format: int32 */
      usage_available_percent: number;
      username: string;
    };
    /** @enum {string} */
    AgentPoolRequestStatus: "pending" | "accepted" | "rejected";
    AgentPoolShareEvidence: {
      /** Format: int32 */
      available_percent: number;
      /** Format: int64 */
      budget_units?: number | null;
      /** Format: int64 */
      cap_units?: number | null;
      fail_open_reason?: string | null;
      /** Format: int32 */
      member_count: number;
      /** Format: int64 */
      pool_cached_tokens: number;
      /** Format: int64 */
      pool_input_tokens: number;
      /** Format: int64 */
      pool_output_tokens: number;
      /** Format: int64 */
      pool_units: number;
      /** Format: double */
      provider_used_percent?: number | null;
      /** Format: int64 */
      remaining_units?: number | null;
      /** Format: int64 */
      user_cached_tokens: number;
      /** Format: int64 */
      user_input_tokens: number;
      /** Format: int64 */
      user_output_tokens: number;
      /** Format: int64 */
      user_units: number;
      window_label?: string | null;
    };
    AgentPoolUsageMetric: {
      detail?: string | null;
      label: string;
      value: string;
    };
    /** @enum {string} */
    AgentProvider: "chatgpt" | "claude" | "gemini" | "deepseek" | "grok";
    AuthenticatedUser: {
      /** Format: uuid */
      id: string;
      recovery_email?: string | null;
      username: string;
    };
    AuthorizeActionRequest: {
      action: string;
      active_contracts?: string[];
      parameters?: unknown;
      plan_id?: string | null;
      step_id?: string | null;
      target?: string | null;
      task: string;
    };
    CompleteAuthorizationRequest: {
      callback_url: string;
    };
    ConnectDeepseekRequest: {
      api_key: string;
    };
    CreateAgentPoolJoinRequest: {
      reason: string;
      telegram: string;
    };
    CreatePlanRequest: {
      available_skills?: string[];
      context_files?: string[];
      task: string;
    };
    CreatedGatewayKey: components["schemas"]["GatewayKey"] & {
      key: string;
    };
    DecideAgentPoolJoinRequest: {
      status: components["schemas"]["AgentPoolRequestStatus"];
    };
    DecideDeviceAuthorization: {
      /** @description true approves and issues a gateway key; false denies. */
      approve: boolean;
      /** @description The short user code shown by the agent, e.g. "XK7P-29QD". */
      user_code: string;
    };
    DeviceAuthorizationStarted: {
      /** @description Secret the agent polls with. Never shown to the operator. */
      device_code: string;
      /** Format: int64 */
      expires_in_seconds: number;
      /** Format: int32 */
      poll_interval_seconds: number;
      /** @description Short code the operator types or clicks to approve, e.g. "XK7P-29QD". */
      user_code: string;
      /** @description Where the operator approves the request. */
      verification_uri: string;
    };
    DeviceAuthorizationToken: {
      /** @description The gateway key. Present only on the first poll after approval. */
      key?: string | null;
      /** @description "pending", "approved" (key present exactly once), or "denied". */
      status: string;
    };
    ErrorResponse: {
      code: string;
      message: string;
    };
    ExecutionPlan: {
      /** Format: date-time */
      created_at: string;
      intent: string;
      plan_id: string;
      prohibited_actions: string[];
      reasoner_model: string;
      required_contracts: string[];
      steps: components["schemas"]["PlanStep"][];
      summary: string;
      verification_criteria: string[];
    };
    GatewayKey: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      last_four: string;
      /** Format: date-time */
      last_used_at?: string | null;
    };
    HealthResponse: {
      service: string;
      status: string;
    };
    InviteAgentPoolMember: {
      username: string;
    };
    LoginRequest: {
      password: string;
      username: string;
    };
    PendingDeviceAuthorization: {
      agent_label: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
      user_code: string;
    };
    PlanStep: {
      action?: string;
      depends_on?: string[];
      id: string;
      rationale?: string | null;
      risk?: string;
      target?: string | null;
      title?: string;
    };
    PollDeviceAuthorization: {
      device_code: string;
    };
    ReasoningDailyStat: {
      /** Format: int64 */
      allowed: number;
      /** Format: int64 */
      blocked: number;
      /** Format: int64 */
      certified: number;
      /** @description Calendar day in ISO format, e.g. "2026-09-26". */
      day: string;
      /** Format: int64 */
      plans: number;
      /** Format: int64 */
      total: number;
    };
    ReasoningEvent: {
      /** Format: date-time */
      created_at: string;
      detail: string;
      /** Format: uuid */
      id: string;
      kind: string;
      outcome: string;
      reasoner_model: string;
      task: string;
    };
    RegisterRequest: {
      password: string;
      recovery_email?: string | null;
      username: string;
    };
    SessionResponse: {
      user: components["schemas"]["AuthenticatedUser"];
    };
    StartAgentConnectionRequest: {
      provider: components["schemas"]["AgentProvider"];
    };
    StartDeviceAuthorization: {
      /** @description Human-readable label the approving operator sees, e.g. "Claude Code on MacBook". */
      agent_label: string;
    };
    VerificationResult: {
      /** Format: float */
      confidence: number;
      findings: string[];
      passed: boolean;
      reasoner_model: string;
      recommendation: string;
      unsatisfied_criteria: string[];
      verification_id: string;
      /** Format: date-time */
      verified_at: string;
    };
    VerifyOutcomeRequest: {
      completed_steps: string[];
      evidence: string;
      modified_files?: string[];
      plan_id?: string | null;
      task: string;
      test_output?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  start_device_authorization: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartDeviceAuthorization"];
      };
    };
    responses: {
      /** @description Device authorization started; poll with the device code */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceAuthorizationStarted"];
        };
      };
      /** @description Invalid agent label */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  decide_device_authorization: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecideDeviceAuthorization"];
      };
    };
    responses: {
      /** @description Authorization approved or denied */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown, expired, or already-decided code */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_pending_authorizations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pending authorization requests awaiting this operator */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PendingDeviceAuthorization"][];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  poll_device_authorization: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PollDeviceAuthorization"];
      };
    };
    responses: {
      /** @description Current authorization status; the key appears exactly once after approval */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceAuthorizationToken"];
        };
      };
      /** @description Unknown or expired device code */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_connections: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user's provider connections */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"][];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  connect_deepseek: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectDeepseekRequest"];
      };
    };
    responses: {
      /** @description DeepSeek API key validated and encrypted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid DeepSeek API key */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description DeepSeek validation unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  start: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartAgentConnectionRequest"];
      };
    };
    responses: {
      /** @description Provider authorization started */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Provider authorization unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_connection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Agent connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Latest provider connection status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  disconnect: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Agent connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Connection credential removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  complete_authorization: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Agent connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteAuthorizationRequest"];
      };
    };
    responses: {
      /** @description Authorization completed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Invalid callback URL */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Provider rejected the exchange */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  refresh_connection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Agent connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Credential refreshed or provider reauthorization started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Provider refresh unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  decide_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Join request identifier */
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecideAgentPoolJoinRequest"];
      };
    };
    responses: {
      /** @description Join request decided */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPoolJoinRequest"];
        };
      };
      /** @description Pool ownership required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Connected account pools */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPool"][];
        };
      };
    };
  };
  invite_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Connected account identifier */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteAgentPoolMember"];
      };
    };
    responses: {
      /** @description Member invited */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPoolPerson"];
        };
      };
      /** @description Pool ownership required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invite rejected */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Connected account identifier */
        connection_id: string;
        /** @description Hub William username */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Member removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Pool ownership required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Membership not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Connected account identifier */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAgentPoolJoinRequest"];
      };
    };
    responses: {
      /** @description Join request created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPoolJoinRequest"];
        };
      };
      /** @description Login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Request rejected */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Session started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Credentials rejected */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid account fields */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session ended */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Access and refresh sessions rotated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Refresh session missing or expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Account created and session started */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Username already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid account fields */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current authenticated user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description No browser session has been started */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No active session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_keys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active gateway keys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayKey"][];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_key: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Gateway key created and returned once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedGatewayKey"];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Connected provider not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  revoke_key: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Gateway key ID */
        key_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Gateway key revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Gateway key not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend is ready to accept requests */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  authorize_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorizeActionRequest"];
      };
    };
    responses: {
      /** @description Action authorized or blocked based on contract boundaries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionDecision"];
        };
      };
      /** @description Gateway key or active authorization required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_events: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Latest reasoning checkpoint events, newest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReasoningEvent"][];
        };
      };
    };
  };
  daily_stats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Per-day reasoning checkpoint counts for the last 365 days */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReasoningDailyStat"][];
        };
      };
    };
  };
  plan_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePlanRequest"];
      };
    };
    responses: {
      /** @description Structured execution plan generated by SERV Reasoning */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionPlan"];
        };
      };
      /** @description Gateway key or active authorization required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  verify_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyOutcomeRequest"];
      };
    };
    responses: {
      /** @description Outcome verification verdict evaluated by SERV Reasoning */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerificationResult"];
        };
      };
      /** @description Gateway key or active authorization required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
